CREATE TYPE skill_type_enum AS ENUM ('LANGUAGE', 'FRAMEWORK', 'TOOL', 'PLATFORM');
CREATE TYPE commit_type_enum AS ENUM ('COMMIT', 'PR');
CREATE TYPE interaction_type_enum AS ENUM ('DESIGNED', 'WROTE', 'REVIEWED');
CREATE TYPE dep_type_enum AS ENUM ('INTERNAL', 'EXTERNAL');

CREATE TABLE engineers (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    team VARCHAR(100),
    join_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_active TIMESTAMP,
    recs JSONB
);
